### ISSUE TITLE
Issue from ka6aH

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO26_Unpredictable_Contract.DYA#1]
1. отстутствует кит у противника 
![image](https://user-images.githubusercontent.com/20025467/72640951-03c11400-397a-11ea-853a-6dff869f477e.png)
![image](https://user-images.githubusercontent.com/20025467/72640981-13d8f380-397a-11ea-903b-357c2acc6965.png)

**Comment by 10Dozen** [comment]
Fixed
